name: CI/CD

on:
  push:
    tags-ignore: [ '**' ]
    branches: [ 'main' ]
    paths:
      - package.json
      - bun.lockb
      - tsconfig.json
      - src/**
      - .storybook/**
      - .github/workflows/cicd.yml

jobs: 
  ci: 
    name: CI
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout and setup
        uses: speelbarrow/checkout-and-setup@v1.2
      - name: Additional setup
        run: |
          bun run build
          sed -E 's#^(import "\.\./)src(/components/index\.js")$#\1dist\2#' .storybook/preview.ts > .storybook/preview.tmp.ts 
          mv .storybook/preview.tmp.ts .storybook/preview.ts
      - name: Run tests
        env:
          SPALL: true
        run: bun test

  CD:       
    uses: speelbarrow/SpeelShap.ES/.github/workflows/release.yml@main
    permissions:
      contents: write
      packages: write
    with:
      source: ${{ github.ref_name }}
      destination: edge
